version: "3.9"

volumes:
  mysql:
    driver: 'local:delegated'
  mongo:
    driver: 'local:delegated'
  redis:
    driver: 'local:delegated'

networks:
  devenv:
    driver: bridge

services:
  nginx:
    build: ./images/nginx
    container_name: devenv_nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${CODE_DIR}:/var/www:delegated
      - ./images/nginx/conf.d:/etc/nginx/conf.d:delegated
    networks:
      devenv:

  redis:
    build: ./images/redis
    container_name: devenv_redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - .data/redis:/data/db:delegated
    networks:
      devenv:

  mysql:
    build: ./images/mysql
    container_name: devenv_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=default
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - .data/mysql:/var/lib/mysql:delegated
    networks:
      devenv:

  # postgres:
  #   build: ./images/postgres
  #   container_name: devenv_postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1
  #   volumes:
  #     - .data/postgres:/var/lib/postgresql:delegated
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   networks:
  #     devenv:

  mongo:
    build: ./images/mongo
    container_name: devenv_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - .data/mongo:/data/db:delegated
    networks:
      devenv:

  php-fpm:
    build: ./images/php-fpm
    container_name: devenv_php-fpm
    restart: always
    volumes:
      - ${CODE_DIR}:/var/www:delegated
    networks:
      devenv:

  # tools
  # adminer:
    # build: ./images/adminer
    # container_name: devenv_adminer
    # restart: always
    # environment:
    #   - ADMINER_DESIGN=pepa-linha
    # ports:
    #   - ${ADMINER_PORT}:8080
    # networks:
    #   devenv:

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: devenv_redis-commander
    restart: always
    depends_on:
      - redis
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      devenv:

